### ISSUE TITLE
Not working with rust 1.17.0

### ISSUE THREAD

**Issue by laibulle** [TrionProg/sphinxad-sys#1]
With Rust 1.17` cargo run` returns this error:

```
error[E0463]: can't find crate for `pkg_config`
 --> /Users/laibulle/.cargo/registry/src/github.com-1ecc6299db9ec823/sphinxad-sys-0.1.2/build.rs:1:1
  |
1 | extern crate pkg_config;
  | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: Could not compile `sphinxad-sys`.
Build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by TrionProg** [comment]
Thank you. I've uploaded new version. I hope it works on 1.7.

**Comment by laibulle** [comment]
It is now fixed.

Thanks
